import { StyleSheet } from 'react-native';

const CreateEventStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        padding: 20,
        paddingBottom: 100,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        height: '10%',
        backgroundColor: '#00A54F',
        width: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
        paddingHorizontal: 20,
        justifyContent: 'center',
    },
    formTitle: {
        fontSize: 30,
        fontWeight: 'bold',
        color: '#00A54F',
        textAlign: 'center',
        marginTop: '0%',
        marginBottom: 20,
    },
    label: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#00A54F',
        marginBottom: 5,
    },
    inputField: {
        height: 50,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 15,
        paddingHorizontal: 10,
        fontSize: 16,
        backgroundColor: '#F9F9F9',
    },
    textAreaField: {
        height: 100,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        fontSize: 16,
        textAlignVertical: 'top',
        backgroundColor: '#F9F9F9',
        marginBottom: 15,
    },
    errorText: {
        color: 'red',
        fontSize: 12,
        marginBottom: 10,
    },
    imageUploadContainer: {
        height: 200,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 15,
        backgroundColor: '#F9F9F9',
    },
    imagePreview: {
        width: '100%',
        height: undefined,
        aspectRatio: 4 / 4,
        borderRadius: 5,
    },
    imagePlaceholder: {
        fontSize: 16,
        color: '#888',
    },
    primaryButton: {
        backgroundColor: '#00A54F',
        paddingVertical: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 20,
    },
    primaryButtonText: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    secondaryButton: {
        backgroundColor: '#FF5733',
        paddingVertical: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 10,
    },
    secondaryButtonText: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
});

export default CreateEventStyles;
